# name of pipeline workflow
name: Rethesh job
# trigger action 
# when there is a push happen in master branch pipeline gonna trigger
on: 
  push:
    branches: [ "main" ]  
    paths-ignore:
      - "README.md"
      - "terraform.tfstate"


jobs:
  provisionjob:
    runs-on: ubuntu-latest
    steps:
    - name: deploy-terraform-resources
      run: |
        terraform init
        terraform plan
        sleep 2
        terraform apply --auto-approve
  destroyjob:
    needs: provisionjob
    runs-on: ubuntu-latest
    steps:
    - name: my first steps
      run: |
        echo "Hello World"
        git version
        whoami
        ls -a

    - name: taking code from repo
      uses: actions/checkout@v5
      with:
        ref: main

    - name: installing Terraform
      uses: hashicorp/setup-terraform@v3

    - name: test github action
      run: |
        echo "Hello World"
        git version
        whoami
        ls -a
        terraform version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: ap-southeast-2

    - name: Verify aws connection
      run: |
        echo "Checking with command"
        aws s3 ls

    - name: destroy-terraform-resources
      run: |
        echo "checking resources"
        terraform destroy



